#!/usr/bin/env python3
"""Fail-closed verifier and generator for the GENOMA v3.4 project-bootstrap attestation.

A VERIFICADO bootstrap attestation is only worth its status if that status can be
reproduced from an immutable input. Prose describing what someone checked is not
evidence, so this module keeps the two halves separate:

* :func:`verify_project_bootstrap` re-derives every bootstrap check from the sealed
  canonical ruleset — a digest-pinned artifact already verified by
  ``scripts/sealed_ruleset.py`` — and returns the evidence behind each answer.
* :func:`verify_bootstrap_attestation` binds an attestation to that re-derived evidence
  and can additionally bind a runtime-generated attestation to an exact Git commit.

Run ``python3 -m scripts.bootstrap_attestation --write --verified-at <ISO8601>`` to
regenerate the attestation; it is generated by execution and must never be edited by hand.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.sealed_ruleset import (
    EXPECTED_DATE,
    EXPECTED_NAME,
    EXPECTED_SHA,
    EXPECTED_VERSION,
    SealedRulesetError,
    decode_verified_payload,
)

ATTESTATION_PATH = ROOT / "deploy" / "attestations" / "bootstrap-project-v3.4.json"
SEALED_DIR = ROOT / "normative" / "sealed"
EXPECTED_FILE_SHA256 = "f7ce057e27a08c1e08c2bb1a74ab6c0fc777f323a852a2d946df344731ee8a2e"
EXPECTED_RULESET_IDENTITY = f"{EXPECTED_VERSION}/VIGENTE/{EXPECTED_DATE}"
EXPECTED_CANONICAL_FILENAME = EXPECTED_NAME
EXPECTED_CANONICAL_SHA256 = EXPECTED_SHA
VERIFIER_ID = "genoma-project-bootstrap-verifier"
VERIFIER_VERSION = "2.0.0"
VERIFIER_COMMAND = "python3 -m scripts.bootstrap_attestation --write"
RESULT_LOCATOR = "deploy/attestations/bootstrap-project-v3.4.json#/checks"
PENDING_STATUS = "PENDENTE"
VERIFIED_STATUS = "VERIFICADO"
FULL_GIT_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
RFC3339_DATETIME_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$"
)
VERIFIED_AT_ERROR = (
    "bootstrap attestation verified_at must be a parseable ISO 8601 datetime in strict RFC 3339 form "
    "with T separator and an explicit timezone offset (Z or ±HH:MM)"
)

# Every bootstrap check is a literal clause of the sealed canonical ruleset. The check is
# satisfied only when the clause is found in the verified payload, so the answer is
# recomputable by anyone holding the same sealed transport.
BOOTSTRAP_CLAUSES: dict[str, str] = {
    "consult_ruleset_before_relevant_genetic_analysis": (
        "Antes de qualquer análise genética relevante, abrir e consultar "
        "REGRAS_PROJETO_GENOMA_VIGENTE_v3.4_2026-08-17.txt"
    ),
    "require_status_vigente": "STATUS NORMATIVO: VIGENTE",
    "require_version_v3_4": "VERSÃO NORMATIVA: v3.4",
    "require_effective_date_2026_08_17": "DATA FORMAL DE EMISSÃO E VIGÊNCIA: 17/08/2026",
    "fail_closed_on_missing_or_conflicting_ruleset": (
        "interromper a análise e declarar RULESET NÃO DISPONÍVEL/CONFLITANTE"
    ),
    "runtime_resource_gate_before_real_calling": (
        "reexecutar o Runtime/Resource Gate antes de calling real"
    ),
    "operational_status_contract_present": (
        "EXECUTADO, VERIFICADO, INFERIDO, PROPOSTO ou NÃO DISPONÍVEL"
    ),
    "post_deployment_requires_live_15_of_15_zero_critical": (
        "executar ao vivo os 15 casos da seção 260, exigindo 15/15 sem falha crítica"
    ),
}
EXPECTED_CHECKS = frozenset(BOOTSTRAP_CLAUSES)


class BootstrapAttestationError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _require_verified_at(value: Any) -> str:
    if not isinstance(value, str) or not value.strip():
        raise BootstrapAttestationError("bootstrap attestation verified_at is missing")
    candidate = value.strip()
    if RFC3339_DATETIME_RE.fullmatch(candidate) is None:
        raise BootstrapAttestationError(VERIFIED_AT_ERROR)
    normalized = candidate[:-1] + "+00:00" if candidate.endswith("Z") else candidate
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError as exc:
        raise BootstrapAttestationError(VERIFIED_AT_ERROR) from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise BootstrapAttestationError(VERIFIED_AT_ERROR)
    return candidate


def _require_source_revision(revision: Any, *, root: Path = ROOT) -> str:
    """Require a full SHA that resolves to that exact commit in the associated repository."""
    if revision == "UNKNOWN":
        raise BootstrapAttestationError("bootstrap attestation source_commit_sha is UNKNOWN")
    if not isinstance(revision, str) or FULL_GIT_SHA_RE.fullmatch(revision) is None:
        raise BootstrapAttestationError(
            "bootstrap attestation source_commit_sha must be a full 40-character lowercase hex Git commit SHA"
        )
    try:
        result = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--verify", f"{revision}^{{commit}}"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError as exc:
        raise BootstrapAttestationError(
            "bootstrap attestation source_commit_sha could not be verified in the associated Git repository"
        ) from exc
    resolved = result.stdout.strip()
    if result.returncode != 0 or resolved != revision:
        raise BootstrapAttestationError(
            "bootstrap attestation source_commit_sha does not resolve to a commit in the associated Git repository"
        )
    return revision


def _source_revision(root: Path) -> str:
    """Repository revision the verifier read, recorded as provenance.

    Unlike the input digests this cannot be recomputed from the attestation alone; it is
    stored so a reader can fetch the exact tree that produced the result.
    """
    try:
        result = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return "UNKNOWN"
    revision = result.stdout.strip()
    return revision if result.returncode == 0 and FULL_GIT_SHA_RE.fullmatch(revision) else "UNKNOWN"


def verify_project_bootstrap(sealed_dir: str | Path = SEALED_DIR) -> dict[str, Any]:
    """Re-derive every bootstrap check from the verified sealed canonical ruleset."""
    raw, transport_evidence = decode_verified_payload(Path(sealed_dir))
    text = raw.decode("utf-8")
    checks: dict[str, Any] = {}
    for name, clause in BOOTSTRAP_CLAUSES.items():
        offset = text.find(clause)
        checks[name] = {
            "satisfied": offset >= 0,
            "clause_sha256": hashlib.sha256(clause.encode("utf-8")).hexdigest(),
            "line": (text.count("\n", 0, offset) + 1) if offset >= 0 else None,
        }
    return {
        "verifier": {
            "id": VERIFIER_ID,
            "version": VERIFIER_VERSION,
            "command": VERIFIER_COMMAND,
        },
        "input": {
            "path": "normative/sealed",
            "canonical_filename": str(transport_evidence["canonical_filename"]),
            "raw_sha256": str(transport_evidence["raw_sha256"]),
            "raw_size_bytes": int(transport_evidence["raw_size_bytes"]),
            "transport_sha256": str(transport_evidence["transport_sha256"]),
        },
        "result_locator": RESULT_LOCATOR,
        "checks": checks,
    }


def _identity_mismatches(payload: dict[str, Any], status: str) -> dict[str, Any]:
    expected_identity = {
        "attestation_type": "GENOMA_PROJECT_BOOTSTRAP",
        "status": status,
        "ruleset_identity": EXPECTED_RULESET_IDENTITY,
        "canonical_filename": EXPECTED_CANONICAL_FILENAME,
        "canonical_sha256": EXPECTED_CANONICAL_SHA256,
        "actor_type": "SERVICE",
        "actor_id": VERIFIER_ID,
    }
    return {
        key: (payload.get(key), expected)
        for key, expected in expected_identity.items()
        if payload.get(key) != expected
    }


def _require_reproducible_method(
    payload: dict[str, Any],
    evidence: dict[str, Any],
    *,
    root: Path = ROOT,
) -> None:
    """The recorded method must be verifier metadata that this run reproduces."""
    method = payload.get("method")
    if not isinstance(method, dict):
        raise BootstrapAttestationError(
            "bootstrap attestation method must be deterministic verifier metadata, not prose"
        )
    if method.get("kind") != "DETERMINISTIC_VERIFIER":
        raise BootstrapAttestationError("bootstrap attestation method kind is not DETERMINISTIC_VERIFIER")
    _require_source_revision(method.get("source_commit_sha"), root=root)
    for field in ("verifier", "input", "result_locator"):
        if method.get(field) != evidence[field]:
            raise BootstrapAttestationError(
                f"bootstrap attestation {field} does not match the verifier that produced this run: "
                f"{method.get(field)!r} != {evidence[field]!r}"
            )
    recorded = method.get("checks_evidence")
    if recorded != evidence["checks"]:
        raise BootstrapAttestationError(
            "bootstrap attestation check evidence is not reproducible from the sealed ruleset"
        )


def verify_bootstrap_attestation(
    path: str | Path = ATTESTATION_PATH,
    *,
    sealed_dir: str | Path = SEALED_DIR,
    root: Path = ROOT,
    expected_source_revision: str | None = None,
    expected_file_sha256: str | None = EXPECTED_FILE_SHA256,
) -> dict[str, Any]:
    """Verify an attestation, optionally binding it to the exact runtime Git revision.

    ``expected_file_sha256`` defaults to the committed, versioned artifact digest. Runtime
    witnesses generate a fresh attestation for their exact merged SHA and therefore pass
    ``None`` here while separately requiring ``expected_source_revision``.
    """
    source = Path(path)
    if not source.is_file():
        raise BootstrapAttestationError("bootstrap attestation is missing")
    raw = source.read_bytes()
    observed_sha = hashlib.sha256(raw).hexdigest()
    if expected_file_sha256 is not None and observed_sha != expected_file_sha256:
        raise BootstrapAttestationError(
            f"bootstrap attestation digest mismatch: expected {expected_file_sha256}, observed {observed_sha}"
        )
    try:
        payload = json.loads(raw)
    except (UnicodeError, json.JSONDecodeError) as exc:
        raise BootstrapAttestationError(f"bootstrap attestation is invalid JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise BootstrapAttestationError("bootstrap attestation must be a JSON object")

    try:
        evidence = verify_project_bootstrap(sealed_dir)
    except (OSError, UnicodeError, ValueError, SealedRulesetError) as exc:
        raise BootstrapAttestationError(
            f"bootstrap checks could not be re-derived from the sealed ruleset: {type(exc).__name__}: {exc}"
        ) from exc

    unsatisfied = sorted(name for name, result in evidence["checks"].items() if not result["satisfied"])
    status = PENDING_STATUS if unsatisfied else VERIFIED_STATUS
    mismatches = _identity_mismatches(payload, status)
    if mismatches:
        raise BootstrapAttestationError(f"bootstrap attestation identity mismatch: {mismatches}")
    if unsatisfied:
        raise BootstrapAttestationError(
            f"bootstrap checks are not satisfied by the sealed ruleset: {unsatisfied}"
        )
    _require_verified_at(payload.get("verified_at"))
    _require_reproducible_method(payload, evidence, root=root)

    method = payload.get("method")
    if not isinstance(method, dict):
        raise BootstrapAttestationError("bootstrap attestation method is missing")
    recorded_source_revision = _require_source_revision(method.get("source_commit_sha"), root=root)
    if expected_source_revision is not None:
        expected_revision = _require_source_revision(expected_source_revision, root=root)
        if recorded_source_revision != expected_revision:
            raise BootstrapAttestationError(
                "bootstrap attestation source_commit_sha does not match the required runtime commit: "
                f"{recorded_source_revision} != {expected_revision}"
            )

    checks = payload.get("checks")
    if not isinstance(checks, dict) or not checks:
        raise BootstrapAttestationError("bootstrap attestation checks are missing or empty")
    if set(checks) != EXPECTED_CHECKS:
        raise BootstrapAttestationError(
            f"bootstrap attestation check set mismatch: expected {sorted(EXPECTED_CHECKS)}, observed {sorted(checks)}"
        )
    failed = sorted(key for key in EXPECTED_CHECKS if checks.get(key) is not True)
    if failed:
        raise BootstrapAttestationError(f"bootstrap attestation has failed checks: {failed}")
    return {
        "status": VERIFIED_STATUS,
        "file_sha256": observed_sha,
        "ruleset_identity": EXPECTED_RULESET_IDENTITY,
        "canonical_sha256": EXPECTED_CANONICAL_SHA256,
        "source_commit_sha": recorded_source_revision,
        "checks_verified": sorted(EXPECTED_CHECKS),
        "verification": evidence,
    }


def build_attestation(
    *,
    sealed_dir: str | Path = SEALED_DIR,
    root: Path = ROOT,
    verified_at: str,
) -> dict[str, Any]:
    """Produce the attestation payload from a verifier run, never from prose."""
    verified_at = _require_verified_at(verified_at)
    evidence = verify_project_bootstrap(sealed_dir)
    source_revision = _require_source_revision(_source_revision(root), root=root)
    unsatisfied = sorted(name for name, result in evidence["checks"].items() if not result["satisfied"])
    return {
        "attestation_type": "GENOMA_PROJECT_BOOTSTRAP",
        "status": PENDING_STATUS if unsatisfied else VERIFIED_STATUS,
        "ruleset_identity": EXPECTED_RULESET_IDENTITY,
        "canonical_filename": EXPECTED_CANONICAL_FILENAME,
        "canonical_sha256": EXPECTED_CANONICAL_SHA256,
        "verified_at": verified_at,
        "actor_type": "SERVICE",
        "actor_id": VERIFIER_ID,
        "method": {
            "kind": "DETERMINISTIC_VERIFIER",
            "verifier": evidence["verifier"],
            "source_commit_sha": source_revision,
            "input": evidence["input"],
            "result_locator": evidence["result_locator"],
            "checks_evidence": evidence["checks"],
        },
        "checks": {name: result["satisfied"] for name, result in evidence["checks"].items()},
        "limitations": (
            "Every check above is re-derived from the sealed canonical ruleset by "
            f"{VERIFIER_COMMAND}; status is PENDENTE unless the verifier satisfies all of them. "
            "The attestation covers the normative bootstrap only: it is not a POST-DEPLOYMENT "
            "PASS, which still requires independent Project Instructions proof plus the live "
            "section-260 smoke. Regenerate this file whenever the canonical ruleset or verifier changes."
        ),
    }


def serialize(payload: dict[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sealed", default=str(SEALED_DIR))
    parser.add_argument("--output", default=str(ATTESTATION_PATH))
    parser.add_argument("--verified-at", required=False)
    parser.add_argument("--write", action="store_true", help="regenerate the attestation file")
    args = parser.parse_args(argv)

    if args.write:
        if not args.verified_at:
            parser.error("--verified-at is required with --write")
        payload = build_attestation(sealed_dir=args.sealed, verified_at=args.verified_at)
        Path(args.output).write_text(serialize(payload), encoding="utf-8")
        print(json.dumps({"written": args.output, "sha256": sha256_file(Path(args.output))}, indent=2))
        return 0

    evidence = verify_bootstrap_attestation(args.output, sealed_dir=args.sealed)
    print(json.dumps(evidence, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
